server:
  servlet:
    context-path: /scraper
  port: 7443
spring:
  batch:
    job:
      enabled: false # Stops the job from running on startup if false
scraper:
  cron:
    expression: 0 30 6 ? * * # Defaults to every morning at 6:30 am, set via --cronexpression
    timezone: America/New_York # Default timezone, set via --timezone
  numberOfDays: 3 # Number of days to run report on, 3 means today, tomorrow, and the next day, set via --numberofdays
mqtt:
  broker:
    address: 192.168.1.121 # Set via --mqttaddress
    port: 1883 # Set via --mqttport