port: 3000
daysToCheck: 3
timezone: America/New_York
timeout: 30000
cronExpression: '0 2 * * *'
maxTries: 1
frigate:
  host: 192.168.1.105
  port: 5000
  use:
    discord: true
    ntfy: true
snapshot:
  path: clips/
  temp: config/snapshots/
  retries: 5