port: 3000
daysToCheck: 3
timezone: America/New_York
timeout: 30000
cronExpression: '0 2 * * *'
maxTries: 10
frigate:
  host: 192.168.1.121
  port: 5000
snapshot:
  path: clips/
  temp: config/snapshots/
  retries: 5